version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j-agent
    ports:
      - "${NEO4J_HTTP_PORT}:7474"  # HTTP UI
      - "${NEO4J_BOLT_PORT}:7687"  # Bolt protocol
    environment:
      NEO4J_AUTH: "${NEO4J_USERNAME}/${NEO4J_PASSWORD}"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - neo4j-data:/data
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u ${NEO4J_USERNAME} -p ${NEO4J_PASSWORD} 'RETURN 1' || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
    restart: always

volumes:
  neo4j-data:
